# Generated by Django 3.0.5 on 2020-04-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='登録時間')),
                ('press_ave_3min', models.FloatField(blank=True, verbose_name='圧力センサ値')),
                ('work_or_sabori', models.FloatField(blank=True, verbose_name='勤怠状況')),
            ],
            options={
                'verbose_name': '採取データ',
                'verbose_name_plural': '採取データ',
            },
        ),
    ]
