# Generated by Django 3.0.5 on 2020-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_num', '0003_log_user_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_label',
            field=models.CharField(blank=True, default='kanta', max_length=50, verbose_name='ユーザー識別'),
        ),
    ]
